<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\StockMovement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ExportController extends Controller
{
    /**
     * Export complete product catalog as professional Excel-ready CSV.
     */
    public function exportProductsCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Products_Catalog_'.date('Y-m-d_His').'.csv';

        $headers = [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ];

        return response()->stream(function () {
            $handle = fopen('php://output', 'w');

            // UTF-8 BOM for Microsoft Excel compatibility
            fprintf($handle, chr(0xEF).chr(0xBB).chr(0xBF));

            $generatedAt = date('Y-m-d H:i:s');
            $generatedBy = Auth::user()?->name ?? 'System Administrator';

            // Calculate aggregate statistics for header summary
            $totalProducts = Product::count();
            $totalUnits = (int) Product::sum('quantity');
            $totalValuation = (float) Product::selectRaw('SUM(price * quantity) as total_val')->value('total_val');
            $lowStockCount = Product::where('quantity', '>', 0)
                ->whereColumn('quantity', '<=', 'low_stock_threshold')
                ->count();
            $outOfStockCount = Product::where('quantity', '<=', 0)->count();

            // Report Header Banner
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, ['HARDWAREHUB - MASTER PRODUCT CATALOG & INVENTORY VALUATION REPORT']);
            fputcsv($handle, ['Generated On:', $generatedAt, 'Generated By:', $generatedBy]);
            fputcsv($handle, ['Total Catalog Items:', $totalProducts, 'Total Physical Stock Units:', $totalUnits]);
            fputcsv($handle, ['Total Inventory Value:', '$ ' . number_format($totalValuation, 2), 'Low Stock Items:', $lowStockCount, 'Out of Stock Items:', $outOfStockCount]);
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, []); // Blank spacer line

            // Column Headers
            fputcsv($handle, [
                'Item #',
                'SKU Code',
                'Product Name',
                'Category',
                'Unit Price ($)',
                'Stock In Hand',
                'Alert Limit',
                'Inventory Health Status',
                'Total Valuation ($)',
                'Product Status',
                'Description',
                'Registered Date',
            ]);

            $rowNumber = 1;
            $runningValuation = 0;
            $runningUnits = 0;

            Product::orderBy('category')->orderBy('name')->chunk(200, function ($products) use ($handle, &$rowNumber, &$runningValuation, &$runningUnits) {
                foreach ($products as $p) {
                    $threshold = $p->low_stock_threshold ?? 10;
                    $valuation = (float) $p->price * (int) $p->quantity;
                    $runningValuation += $valuation;
                    $runningUnits += (int) $p->quantity;

                    $healthStatus = match (true) {
                        $p->quantity <= 0 => 'OUT OF STOCK (CRITICAL)',
                        $p->quantity <= $threshold => 'LOW STOCK (REORDER REQUIRED)',
                        default => 'HEALTHY STOCK',
                    };

                    fputcsv($handle, [
                        $rowNumber++,
                        $p->sku,
                        $p->name,
                        $p->category ?? 'General',
                        '$ ' . number_format((float) $p->price, 2),
                        $p->quantity . ' units',
                        $threshold . ' units',
                        $healthStatus,
                        '$ ' . number_format($valuation, 2),
                        strtoupper($p->status),
                        $p->description ?? '-',
                        $p->created_at?->format('Y-m-d H:i:s') ?? '-',
                    ]);
                }
            });

            // Summary Footer Row
            fputcsv($handle, []);
            fputcsv($handle, [
                'TOTAL SUMMARY',
                '',
                "Total Products: {$totalProducts}",
                '',
                '',
                "{$runningUnits} units",
                '',
                '',
                '$ ' . number_format($runningValuation, 2),
                '',
                '',
                ''
            ]);

            fclose($handle);
        }, 200, $headers);
    }

    /**
     * Export low-stock purchase replenishment list as CSV.
     */
    public function exportLowStockCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Low_Stock_Replenishment_'.date('Y-m-d_His').'.csv';

        $headers = [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ];

        return response()->stream(function () {
            $handle = fopen('php://output', 'w');
            fprintf($handle, chr(0xEF).chr(0xBB).chr(0xBF));

            $generatedAt = date('Y-m-d H:i:s');
            $generatedBy = Auth::user()?->name ?? 'System Administrator';

            $lowStockProducts = Product::where('status', 'active')
                ->where(function ($q) {
                    $q->where('quantity', '<=', 0)
                      ->orWhereColumn('quantity', '<=', 'low_stock_threshold');
                })
                ->orderBy('quantity')
                ->get();

            $totalItemsToReorder = $lowStockProducts->count();
            $totalEstRestockCost = 0;
            $totalUnitsToOrder = 0;

            foreach ($lowStockProducts as $p) {
                $threshold = $p->low_stock_threshold ?? 10;
                $suggested = max(10, ($threshold * 2) - $p->quantity);
                $totalUnitsToOrder += $suggested;
                $totalEstRestockCost += ($suggested * (float) $p->price);
            }

            // Report Header Banner
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, ['HARDWAREHUB - LOW STOCK REPLENISHMENT & REORDER PURCHASE SHEET']);
            fputcsv($handle, ['Generated On:', $generatedAt, 'Generated By:', $generatedBy]);
            fputcsv($handle, ['Critical Items Requiring Purchase:', $totalItemsToReorder, 'Total Units Suggested to Order:', $totalUnitsToOrder]);
            fputcsv($handle, ['Estimated Total Replenishment Cost:', '$ ' . number_format($totalEstRestockCost, 2)]);
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, []);

            // Table Headers
            fputcsv($handle, [
                'Priority #',
                'SKU Code',
                'Product Name',
                'Category',
                'Current Stock',
                'Alert Threshold',
                'Suggested Reorder Qty',
                'Unit Price ($)',
                'Est. Reorder Cost ($)',
                'Urgency Level',
            ]);

            $priority = 1;
            foreach ($lowStockProducts as $p) {
                $threshold = $p->low_stock_threshold ?? 10;
                $suggestedReorder = max(10, ($threshold * 2) - $p->quantity);
                $estCost = $suggestedReorder * (float) $p->price;
                $urgency = $p->quantity <= 0 ? 'CRITICAL - OUT OF STOCK' : 'HIGH - BELOW THRESHOLD';

                fputcsv($handle, [
                    $priority++,
                    $p->sku,
                    $p->name,
                    $p->category ?? 'General',
                    $p->quantity . ' units',
                    $threshold . ' units',
                    $suggestedReorder . ' units',
                    '$ ' . number_format((float) $p->price, 2),
                    '$ ' . number_format($estCost, 2),
                    $urgency,
                ]);
            }

            // Summary Footer Row
            fputcsv($handle, []);
            fputcsv($handle, [
                'TOTAL PURCHASE ESTIMATE',
                '',
                "{$totalItemsToReorder} Products",
                '',
                '',
                '',
                "{$totalUnitsToOrder} Units",
                '',
                '$ ' . number_format($totalEstRestockCost, 2),
                ''
            ]);

            fclose($handle);
        }, 200, $headers);
    }

    /**
     * Export stock movement history audit log as CSV.
     */
    public function exportStockMovementsCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Stock_Movements_Ledger_'.date('Y-m-d_His').'.csv';

        $headers = [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ];

        return response()->stream(function () {
            $handle = fopen('php://output', 'w');
            fprintf($handle, chr(0xEF).chr(0xBB).chr(0xBF));

            $generatedAt = date('Y-m-d H:i:s');
            $generatedBy = Auth::user()?->name ?? 'System Administrator';
            $totalMovements = StockMovement::count();
            $totalIn = StockMovement::where('type', 'in')->count();
            $totalOut = StockMovement::where('type', 'out')->count();
            $totalAdj = StockMovement::whereIn('type', ['adjustment', 'damage'])->count();

            // Report Header Banner
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, ['HARDWAREHUB - INVENTORY STOCK MOVEMENTS & AUDIT TRAIL LEDGER']);
            fputcsv($handle, ['Generated On:', $generatedAt, 'Generated By:', $generatedBy]);
            fputcsv($handle, ['Total Audit Records:', $totalMovements, 'Stock In Arrivals:', $totalIn, 'Stock Out Dispatches:', $totalOut, 'Audits/Adjustments:', $totalAdj]);
            fputcsv($handle, ['========================================================================================']);
            fputcsv($handle, []);

            // Table Headers
            fputcsv($handle, [
                'Audit Log ID',
                'Date & Time',
                'SKU Code',
                'Product Name',
                'Movement Type',
                'Qty Change',
                'Previous Stock',
                'New Stock Balance',
                'Performed By (User)',
                'Reason / Reference Note',
            ]);

            StockMovement::with(['product' => fn ($q) => $q->withTrashed(), 'user'])
                ->latest()
                ->chunk(200, function ($movements) use ($handle) {
                    foreach ($movements as $m) {
                        $typeLabel = match ($m->type) {
                            'in' => 'STOCK IN (Restock)',
                            'out' => 'STOCK OUT (Sale / Dispatch)',
                            'damage' => 'DAMAGE (Write-off)',
                            default => 'ADJUSTMENT (Audit)',
                        };

                        $qtyChangeFormatted = $m->quantity_changed > 0 
                            ? "+{$m->quantity_changed} units" 
                            : "{$m->quantity_changed} units";

                        fputcsv($handle, [
                            'LOG-' . str_pad($m->id, 5, '0', STR_PAD_LEFT),
                            $m->created_at?->format('Y-m-d H:i:s') ?? '-',
                            $m->product?->sku ?? 'DELETED',
                            $m->product?->name ?? 'Archived Item',
                            $typeLabel,
                            $qtyChangeFormatted,
                            $m->previous_stock . ' units',
                            $m->new_stock . ' units',
                            $m->user?->name ?? 'System / Admin',
                            $m->reason ?? 'Routine inventory operation',
                        ]);
                    }
                });

            fclose($handle);
        }, 200, $headers);
    }
}

