<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\StockMovement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ExportController extends Controller
{
    /**
     * Export complete product catalog as a beautifully formatted Excel (.xlsx) spreadsheet.
     */
    public function exportProductsCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Products_Catalog_' . date('Y-m-d_His') . '.xlsx';

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Products Catalog');
        $sheet->setShowGridLines(true);

        $generatedAt = date('Y-m-d H:i:s');
        $generatedBy = Auth::user()?->name ?? 'System Administrator';

        $totalProducts = Product::count();
        $totalUnits = (int) Product::sum('quantity');
        $totalValuation = (float) Product::selectRaw('SUM(price * quantity) as total_val')->value('total_val');
        $lowStockCount = Product::where('quantity', '>', 0)
            ->whereColumn('quantity', '<=', 'low_stock_threshold')
            ->count();
        $outOfStockCount = Product::where('quantity', '<=', 0)->count();

        // 1. Top Brand Banner (Row 1-2)
        $sheet->mergeCells('A1:L1');
        $sheet->setCellValue('A1', 'HARDWAREHUB — MASTER PRODUCT CATALOG & INVENTORY VALUATION');
        $sheet->getRowDimension(1)->setRowHeight(36);
        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 14, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1E1B4B']], // Dark Indigo Navy
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);

        // 2. Metadata Information Strip (Row 3-4)
        $sheet->setCellValue('A3', 'Generated On:');
        $sheet->setCellValue('B3', $generatedAt);
        $sheet->setCellValue('D3', 'Generated By:');
        $sheet->setCellValue('E3', $generatedBy);
        $sheet->setCellValue('G3', 'Catalog Total Items:');
        $sheet->setCellValue('H3', $totalProducts . ' products');
        $sheet->setCellValue('J3', 'Total Stock In Hand:');
        $sheet->setCellValue('K3', number_format($totalUnits) . ' units');

        $sheet->setCellValue('A4', 'Total Valuation:');
        $sheet->setCellValue('B4', '$ ' . number_format($totalValuation, 2));
        $sheet->setCellValue('D4', 'Low Stock Alert:');
        $sheet->setCellValue('E4', $lowStockCount . ' items');
        $sheet->setCellValue('G4', 'Out of Stock:');
        $sheet->setCellValue('H4', $outOfStockCount . ' items');
        $sheet->setCellValue('J4', 'System Status:');
        $sheet->setCellValue('K4', 'ACTIVE & VERIFIED');

        $sheet->getStyle('A3:L4')->applyFromArray([
            'font' => ['size' => 10, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'F8FAFC']],
        ]);
        $sheet->getStyle('A3')->getFont()->setBold(true);
        $sheet->getStyle('D3')->getFont()->setBold(true);
        $sheet->getStyle('G3')->getFont()->setBold(true);
        $sheet->getStyle('J3')->getFont()->setBold(true);
        $sheet->getStyle('A4')->getFont()->setBold(true);
        $sheet->getStyle('D4')->getFont()->setBold(true);
        $sheet->getStyle('G4')->getFont()->setBold(true);
        $sheet->getStyle('J4')->getFont()->setBold(true);

        // 3. Table Column Headers (Row 6)
        $headers = [
            'A6' => 'Item #',
            'B6' => 'SKU Code',
            'C6' => 'Product Name',
            'D6' => 'Category',
            'E6' => 'Unit Price ($)',
            'F6' => 'Stock In Hand',
            'G6' => 'Alert Limit',
            'H6' => 'Stock Health Status',
            'I6' => 'Total Valuation ($)',
            'J6' => 'Product Status',
            'K6' => 'Description / Specifications',
            'L6' => 'Registered Date & Time',
        ];

        foreach ($headers as $cell => $text) {
            $sheet->setCellValue($cell, $text);
        }

        $sheet->getRowDimension(6)->setRowHeight(28);
        $sheet->getStyle('A6:L6')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 10.5, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4338CA']], // Modern Indigo
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => '6366F1']]],
        ]);

        // 4. Populate Data Rows
        $products = Product::orderBy('category')->orderBy('name')->get();
        $currentRow = 7;
        $rowNumber = 1;
        $runningValuation = 0;
        $runningUnits = 0;

        foreach ($products as $p) {
            $threshold = $p->low_stock_threshold ?? 10;
            $valuation = (float) $p->price * (int) $p->quantity;
            $runningValuation += $valuation;
            $runningUnits += (int) $p->quantity;

            $health = match (true) {
                $p->quantity <= 0 => 'OUT OF STOCK',
                $p->quantity <= $threshold => 'LOW STOCK',
                default => 'HEALTHY',
            };

            $sheet->setCellValue("A{$currentRow}", $rowNumber++);
            $sheet->setCellValue("B{$currentRow}", $p->sku);
            $sheet->setCellValue("C{$currentRow}", $p->name);
            $sheet->setCellValue("D{$currentRow}", $p->category ?? 'General');
            $sheet->setCellValue("E{$currentRow}", (float) $p->price);
            $sheet->setCellValue("F{$currentRow}", (int) $p->quantity);
            $sheet->setCellValue("G{$currentRow}", (int) $threshold);
            $sheet->setCellValue("H{$currentRow}", $health);
            $sheet->setCellValue("I{$currentRow}", (float) $valuation);
            $sheet->setCellValue("J{$currentRow}", strtoupper($p->status));
            $sheet->setCellValue("K{$currentRow}", $p->description ?? '—');
            $sheet->setCellValue("L{$currentRow}", $p->created_at?->format('Y-m-d H:i:s') ?? '—');

            // Format numbers & currencies
            $sheet->getStyle("E{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');
            $sheet->getStyle("F{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("G{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("I{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');

            // Alignments
            $sheet->getStyle("A{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("B{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("D{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("E{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("F{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("G{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("H{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("J{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("L{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            // Row zebra striping
            $rowBg = ($currentRow % 2 === 0) ? 'F8FAFC' : 'FFFFFF';
            $sheet->getStyle("A{$currentRow}:L{$currentRow}")->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Segoe UI'],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $rowBg]],
                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => 'E2E8F0']]],
            ]);

            // Highlight Stock Health Badge
            if ($health === 'HEALTHY') {
                $sheet->getStyle("H{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '166534']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'DCFCE7']],
                ]);
            } elseif ($health === 'LOW STOCK') {
                $sheet->getStyle("H{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '9A3412']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEF3C7']],
                ]);
            } else {
                $sheet->getStyle("H{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '991B1B']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEE2E2']],
                ]);
            }

            // Highlight SKU
            $sheet->getStyle("B{$currentRow}")->getFont()->setName('Consolas')->setSize(9.5);

            $sheet->getRowDimension($currentRow)->setRowHeight(22);
            $currentRow++;
        }

        // 5. Total Summary Row
        $sheet->mergeCells("A{$currentRow}:D{$currentRow}");
        $sheet->setCellValue("A{$currentRow}", 'TOTAL PORTFOLIO SUMMARY');
        $sheet->setCellValue("F{$currentRow}", $runningUnits);
        $sheet->setCellValue("I{$currentRow}", $runningValuation);

        $sheet->getStyle("F{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
        $sheet->getStyle("I{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');

        $sheet->getRowDimension($currentRow)->setRowHeight(26);
        $sheet->getStyle("A{$currentRow}:L{$currentRow}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => '1E293B'], 'size' => 11, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E2E8F0']],
            'borders' => [
                'top' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => '94A3B8']],
                'bottom' => ['borderStyle' => Border::BORDER_DOUBLE, 'color' => ['rgb' => '475569']],
            ],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getStyle("A{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
        $sheet->getStyle("F{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        $sheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        // 6. Explicit Column Widths for Ultra Crisp Visibility (NO '########' and NO text truncation)
        $columnWidths = [
            'A' => 10,  // Item #
            'B' => 18,  // SKU Code
            'C' => 34,  // Product Name
            'D' => 20,  // Category
            'E' => 16,  // Unit Price
            'F' => 18,  // Stock In Hand
            'G' => 16,  // Alert Limit
            'H' => 24,  // Stock Health Status
            'I' => 22,  // Total Valuation
            'J' => 18,  // Product Status
            'K' => 38,  // Description
            'L' => 24,  // Registered Date
        ];

        foreach ($columnWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        $writer = new Xlsx($spreadsheet);

        return response()->stream(function () use ($writer) {
            $writer->save('php://output');
        }, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ]);
    }

    /**
     * Export low-stock replenishment purchase order as formatted Excel (.xlsx).
     */
    public function exportLowStockCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Low_Stock_Replenishment_' . date('Y-m-d_His') . '.xlsx';

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Replenishment Sheet');
        $sheet->setShowGridLines(true);

        $generatedAt = date('Y-m-d H:i:s');
        $generatedBy = Auth::user()?->name ?? 'System Administrator';

        $lowStockProducts = Product::where('status', 'active')
            ->where(function ($q) {
                $q->where('quantity', '<=', 0)
                  ->orWhereColumn('quantity', '<=', 'low_stock_threshold');
            })
            ->orderBy('quantity')
            ->get();

        $totalItemsToReorder = $lowStockProducts->count();
        $totalEstRestockCost = 0;
        $totalUnitsToOrder = 0;

        foreach ($lowStockProducts as $p) {
            $threshold = $p->low_stock_threshold ?? 10;
            $suggested = max(10, ($threshold * 2) - $p->quantity);
            $totalUnitsToOrder += $suggested;
            $totalEstRestockCost += ($suggested * (float) $p->price);
        }

        // Top Banner
        $sheet->mergeCells('A1:J1');
        $sheet->setCellValue('A1', 'HARDWAREHUB — LOW STOCK REPLENISHMENT & REORDER PURCHASE SHEET');
        $sheet->getRowDimension(1)->setRowHeight(36);
        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 13.5, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '7C2D12']], // Deep Amber / Crimson
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);

        // Meta Info
        $sheet->setCellValue('A3', 'Generated On:');
        $sheet->setCellValue('B3', $generatedAt);
        $sheet->setCellValue('D3', 'Generated By:');
        $sheet->setCellValue('E3', $generatedBy);
        $sheet->setCellValue('G3', 'Critical Items to Reorder:');
        $sheet->setCellValue('H3', $totalItemsToReorder . ' products');

        $sheet->setCellValue('A4', 'Total Units Needed:');
        $sheet->setCellValue('B4', number_format($totalUnitsToOrder) . ' units');
        $sheet->setCellValue('D4', 'Est. Purchase Budget:');
        $sheet->setCellValue('E4', '$ ' . number_format($totalEstRestockCost, 2));
        $sheet->setCellValue('G4', 'Priority Level:');
        $sheet->setCellValue('H4', 'URGENT PURCHASE ACTION');

        $sheet->getStyle('A3:J4')->applyFromArray([
            'font' => ['size' => 10, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEF2F2']],
        ]);
        $sheet->getStyle('A3')->getFont()->setBold(true);
        $sheet->getStyle('D3')->getFont()->setBold(true);
        $sheet->getStyle('G3')->getFont()->setBold(true);
        $sheet->getStyle('A4')->getFont()->setBold(true);
        $sheet->getStyle('D4')->getFont()->setBold(true);
        $sheet->getStyle('G4')->getFont()->setBold(true);

        // Headers
        $headers = [
            'A6' => 'Priority #',
            'B6' => 'SKU Code',
            'C6' => 'Product Name',
            'D6' => 'Category',
            'E6' => 'Current Stock',
            'F6' => 'Alert Limit',
            'G6' => 'Suggested Reorder Qty',
            'H6' => 'Unit Price ($)',
            'I6' => 'Est. Reorder Cost ($)',
            'J6' => 'Reorder Urgency',
        ];

        foreach ($headers as $cell => $text) {
            $sheet->setCellValue($cell, $text);
        }

        $sheet->getRowDimension(6)->setRowHeight(28);
        $sheet->getStyle('A6:J6')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 10.5, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'C2410C']], // Orange / Amber
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'EA580C']]],
        ]);

        $currentRow = 7;
        $priority = 1;

        foreach ($lowStockProducts as $p) {
            $threshold = $p->low_stock_threshold ?? 10;
            $suggestedReorder = max(10, ($threshold * 2) - $p->quantity);
            $estCost = $suggestedReorder * (float) $p->price;
            $isOutOfStock = $p->quantity <= 0;
            $urgency = $isOutOfStock ? 'CRITICAL (OUT OF STOCK)' : 'HIGH (BELOW THRESHOLD)';

            $sheet->setCellValue("A{$currentRow}", $priority++);
            $sheet->setCellValue("B{$currentRow}", $p->sku);
            $sheet->setCellValue("C{$currentRow}", $p->name);
            $sheet->setCellValue("D{$currentRow}", $p->category ?? 'General');
            $sheet->setCellValue("E{$currentRow}", (int) $p->quantity);
            $sheet->setCellValue("F{$currentRow}", (int) $threshold);
            $sheet->setCellValue("G{$currentRow}", (int) $suggestedReorder);
            $sheet->setCellValue("H{$currentRow}", (float) $p->price);
            $sheet->setCellValue("I{$currentRow}", (float) $estCost);
            $sheet->setCellValue("J{$currentRow}", $urgency);

            $sheet->getStyle("E{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("F{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("G{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("H{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');
            $sheet->getStyle("I{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');

            $sheet->getStyle("A{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("B{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("D{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("E{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("F{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("G{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("H{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("J{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            $rowBg = ($currentRow % 2 === 0) ? 'FFFBEB' : 'FFFFFF';
            $sheet->getStyle("A{$currentRow}:J{$currentRow}")->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Segoe UI'],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $rowBg]],
                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => 'FED7AA']]],
            ]);

            if ($isOutOfStock) {
                $sheet->getStyle("J{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '991B1B']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEE2E2']],
                ]);
            } else {
                $sheet->getStyle("J{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '9A3412']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEF3C7']],
                ]);
            }

            $sheet->getStyle("B{$currentRow}")->getFont()->setName('Consolas')->setSize(9.5);
            $sheet->getRowDimension($currentRow)->setRowHeight(22);
            $currentRow++;
        }

        // Summary Row
        $sheet->mergeCells("A{$currentRow}:D{$currentRow}");
        $sheet->setCellValue("A{$currentRow}", 'TOTAL ESTIMATED PURCHASE BUDGET');
        $sheet->setCellValue("G{$currentRow}", $totalUnitsToOrder);
        $sheet->setCellValue("I{$currentRow}", $totalEstRestockCost);

        $sheet->getStyle("G{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
        $sheet->getStyle("I{$currentRow}")->getNumberFormat()->setFormatCode('"$"#,##0.00');

        $sheet->getRowDimension($currentRow)->setRowHeight(26);
        $sheet->getStyle("A{$currentRow}:J{$currentRow}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => '7C2D12'], 'size' => 11, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FFEDD5']],
            'borders' => [
                'top' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'FDBA74']],
                'bottom' => ['borderStyle' => Border::BORDER_DOUBLE, 'color' => ['rgb' => 'C2410C']],
            ],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getStyle("A{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
        $sheet->getStyle("G{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        $sheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        $columnWidths = [
            'A' => 12,  // Priority #
            'B' => 18,  // SKU Code
            'C' => 34,  // Product Name
            'D' => 20,  // Category
            'E' => 18,  // Current Stock
            'F' => 16,  // Alert Limit
            'G' => 24,  // Suggested Reorder
            'H' => 16,  // Unit Price
            'I' => 24,  // Est. Cost
            'J' => 28,  // Urgency
        ];

        foreach ($columnWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        $writer = new Xlsx($spreadsheet);

        return response()->stream(function () use ($writer) {
            $writer->save('php://output');
        }, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ]);
    }

    /**
     * Export stock movement history audit log as formatted Excel (.xlsx).
     */
    public function exportStockMovementsCsv(Request $request): StreamedResponse
    {
        $filename = 'HardwareHub_Stock_Movements_Ledger_' . date('Y-m-d_His') . '.xlsx';

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Movements Ledger');
        $sheet->setShowGridLines(true);

        $generatedAt = date('Y-m-d H:i:s');
        $generatedBy = Auth::user()?->name ?? 'System Administrator';
        $totalMovements = StockMovement::count();
        $totalIn = StockMovement::where('type', 'in')->count();
        $totalOut = StockMovement::where('type', 'out')->count();
        $totalAdj = StockMovement::whereIn('type', ['adjustment', 'damage'])->count();

        // Top Banner
        $sheet->mergeCells('A1:J1');
        $sheet->setCellValue('A1', 'HARDWAREHUB — INVENTORY STOCK MOVEMENTS & AUDIT LEDGER');
        $sheet->getRowDimension(1)->setRowHeight(36);
        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 13.5, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '0F172A']], // Deep Slate
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);

        // Meta Info
        $sheet->setCellValue('A3', 'Generated On:');
        $sheet->setCellValue('B3', $generatedAt);
        $sheet->setCellValue('D3', 'Generated By:');
        $sheet->setCellValue('E3', $generatedBy);
        $sheet->setCellValue('G3', 'Total Audit Records:');
        $sheet->setCellValue('H3', $totalMovements . ' entries');

        $sheet->setCellValue('A4', 'Stock In Arrivals:');
        $sheet->setCellValue('B4', $totalIn . ' events');
        $sheet->setCellValue('D4', 'Stock Out Dispatches:');
        $sheet->setCellValue('E4', $totalOut . ' events');
        $sheet->setCellValue('G4', 'Adjustments/Audits:');
        $sheet->setCellValue('H4', $totalAdj . ' events');

        $sheet->getStyle('A3:J4')->applyFromArray([
            'font' => ['size' => 10, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'F1F5F9']],
        ]);
        $sheet->getStyle('A3')->getFont()->setBold(true);
        $sheet->getStyle('D3')->getFont()->setBold(true);
        $sheet->getStyle('G3')->getFont()->setBold(true);
        $sheet->getStyle('A4')->getFont()->setBold(true);
        $sheet->getStyle('D4')->getFont()->setBold(true);
        $sheet->getStyle('G4')->getFont()->setBold(true);

        // Headers
        $headers = [
            'A6' => 'Audit Log ID',
            'B6' => 'Event Timestamp',
            'C6' => 'SKU Code',
            'D6' => 'Product Name',
            'E6' => 'Movement Type',
            'F6' => 'Quantity Change',
            'G6' => 'Previous Stock',
            'H6' => 'New Stock Balance',
            'I6' => 'Operator / User',
            'J6' => 'Reason & Notes',
        ];

        foreach ($headers as $cell => $text) {
            $sheet->setCellValue($cell, $text);
        }

        $sheet->getRowDimension(6)->setRowHeight(28);
        $sheet->getStyle('A6:J6')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 10.5, 'name' => 'Segoe UI'],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '334155']], // Slate Navy
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => '475569']]],
        ]);

        $movements = StockMovement::with(['product' => fn ($q) => $q->withTrashed(), 'user'])
            ->latest()
            ->get();

        $currentRow = 7;
        foreach ($movements as $m) {
            $typeLabel = match ($m->type) {
                'in' => 'STOCK IN (Restock)',
                'out' => 'STOCK OUT (Sale/Dispatch)',
                'damage' => 'DAMAGE (Write-off)',
                default => 'ADJUSTMENT (Audit)',
            };

            $qtyFormatted = ($m->quantity_changed > 0 ? '+' : '') . $m->quantity_changed;

            $sheet->setCellValue("A{$currentRow}", 'LOG-' . str_pad($m->id, 5, '0', STR_PAD_LEFT));
            $sheet->setCellValue("B{$currentRow}", $m->created_at?->format('Y-m-d H:i:s') ?? '—');
            $sheet->setCellValue("C{$currentRow}", $m->product?->sku ?? 'ARCHIVED');
            $sheet->setCellValue("D{$currentRow}", $m->product?->name ?? 'Deleted Item');
            $sheet->setCellValue("E{$currentRow}", $typeLabel);
            $sheet->setCellValue("F{$currentRow}", $qtyFormatted . ' units');
            $sheet->setCellValue("G{$currentRow}", (int) $m->previous_stock);
            $sheet->setCellValue("H{$currentRow}", (int) $m->new_stock);
            $sheet->setCellValue("I{$currentRow}", $m->user?->name ?? 'System Administrator');
            $sheet->setCellValue("J{$currentRow}", $m->reason ?? 'Routine inventory operation');

            $sheet->getStyle("G{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');
            $sheet->getStyle("H{$currentRow}")->getNumberFormat()->setFormatCode('#,##0" units"');

            $sheet->getStyle("A{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("B{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("C{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("E{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle("F{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("G{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("H{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle("I{$currentRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            $rowBg = ($currentRow % 2 === 0) ? 'F8FAFC' : 'FFFFFF';
            $sheet->getStyle("A{$currentRow}:J{$currentRow}")->applyFromArray([
                'font' => ['size' => 10, 'name' => 'Segoe UI'],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $rowBg]],
                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => 'CBD5E1']]],
            ]);

            // Highlight Movement Type
            if ($m->type === 'in') {
                $sheet->getStyle("E{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '166534']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'DCFCE7']],
                ]);
            } elseif ($m->type === 'out') {
                $sheet->getStyle("E{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '1E40AF']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'DBEAFE']],
                ]);
            } else {
                $sheet->getStyle("E{$currentRow}")->applyFromArray([
                    'font' => ['bold' => true, 'color' => ['rgb' => '9A3412']],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'FEF3C7']],
                ]);
            }

            $sheet->getStyle("A{$currentRow}")->getFont()->setName('Consolas')->setSize(9.5);
            $sheet->getStyle("C{$currentRow}")->getFont()->setName('Consolas')->setSize(9.5);
            $sheet->getRowDimension($currentRow)->setRowHeight(22);
            $currentRow++;
        }

        $columnWidths = [
            'A' => 16,  // Log ID
            'B' => 24,  // Timestamp
            'C' => 18,  // SKU Code
            'D' => 32,  // Product Name
            'E' => 28,  // Movement Type
            'F' => 18,  // Quantity Change
            'G' => 18,  // Previous Stock
            'H' => 20,  // New Stock Balance
            'I' => 24,  // Operator
            'J' => 38,  // Reason
        ];

        foreach ($columnWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        $writer = new Xlsx($spreadsheet);

        return response()->stream(function () use ($writer) {
            $writer->save('php://output');
        }, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ]);
    }
}
